# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\erser\Desktop\pythonn 3.8\Proje\_projectForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.followerList = QtWidgets.QListWidget(self.centralwidget)
        self.followerList.setGeometry(QtCore.QRect(390, 10, 331, 601))
        self.followerList.setObjectName("followerList")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 361, 241))
        self.groupBox.setObjectName("groupBox")
        self.lblResult = QtWidgets.QLabel(self.groupBox)
        self.lblResult.setGeometry(QtCore.QRect(10, 180, 331, 41))
        self.lblResult.setObjectName("lblResult")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 341, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.linePassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.linePassword.setObjectName("linePassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.linePassword)
        self.lineUsername = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineUsername.setObjectName("lineUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineUsername)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.btnLogin = QtWidgets.QPushButton(self.groupBox)
        self.btnLogin.setGeometry(QtCore.QRect(10, 120, 341, 41))
        self.btnLogin.setObjectName("btnLogin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Login"))
        self.lblResult.setText(_translate("MainWindow", "Waiting"))
        self.label.setText(_translate("MainWindow", "Username:"))
        self.label_2.setText(_translate("MainWindow", "Password: "))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
